name: Laravel

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.4.1"
      - uses: actions/checkout@v4
      - name: Copy .env
        working-directory: exitpoll
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        working-directory: exitpoll
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs && npm install
      - name: Generate key
        working-directory: exitpoll
        run: php artisan key:generate
      - name: Directory Permissions
        working-directory: exitpoll
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        working-directory: exitpoll
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Install Node dependencies
        working-directory: exitpoll
        run: npm ci
      - name: Build assets
        working-directory: exitpoll
        run: npm run build
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        working-directory: exitpoll
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan migrate:fresh --seed --force && php artisan test
